name: Build and test

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    types: [opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Continue with other matrix items if one fails
      matrix:
        variant: [ 'play', 'website', 'huawei', 'fdroid' ]
        build_type: [ 'qa' ]
        include:
          - variant: 'huawei'
            extra_build_command_options: '-Phuawei=1'
          - variant: 'play'
            run_test: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties') }}-${{ matrix.variant }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with gradle
        id: build
        run: ./gradlew assemble${{ matrix.variant }}${{ matrix.build_type }} ${{ matrix.extra_build_command_options }}

      - name: Run unit tests
        if: ${{ matrix.run_test == true }}
        id: test
        run: ./gradlew test${{ matrix.variant }}${{ matrix.build_type }}UnitTest ${{ matrix.extra_build_command_options }}

      - name: Upload build reports regardless
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports-${{ matrix.variant }}-${{ matrix.build_type }}
          path: app/build/reports
          if-no-files-found: ignore

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: session-${{ matrix.variant }}-${{ matrix.build_type }}
          path: app/build/outputs/apk/${{ matrix.variant }}/${{ matrix.build_type }}/*-universal*apk
          if-no-files-found: error
          compression-level: 0
